@PasswordGeneratorApi_HostAddress = http://localhost:5180

GET {{PasswordGeneratorApi_HostAddress}}/password
Accept: application/json

###

POST {{PasswordGeneratorApi_HostAddress}}/password
Content-Type: application/json

{
  "length": 20,
  "includeUppercase": true,
  "includeLowercase": true,
  "includeNumbers": true,
  "includeSpecialCharacters": true,
  "excludedCharacters": "0O1l"
}

###
